name: Run app.py and Commit data.json

on:
  schedule:
      - cron: '0 4 * * 1,2,4,5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: python app.py

    - name: Commit and push
      run: |
        git config --local user.email "clintontedja@gmail.com"
        git config --local user.name "Clinton Tedja"
        git add data.json
        git commit -m "Update data.json output" || echo "No changes to commit"
        git pull --rebase origin main
        git push "https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/ctedja/regional_evidence.git" HEAD:main